#  -*-makefile-*- Makefile 
#  -----------------------------------------------------------------------------
#  Copyright 2012 Dietmar Kuehl http://www.dietmar-kuehl.de              
#  Distributed under the Boost Software License, Version 1.0. (See file  
#  LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt).     
#  -----------------------------------------------------------------------------

default: property_map_find

#  -----------------------------------------------------------------------------

CC       = $(CXX)
CXXFLAGS = -W -Wall -std=c++11

clean:
	$(RM) property_map_find
	$(RM) mkerr olderr *~
