#!/usr/bin/python

import sys
import re

inc_re  = re.compile(r"#include <(.*)>")
comp_re = re.compile(r"#include <(.*).hpp>")
name_re = re.compile(r"namespace")
end_re  = re.compile(r"#endif")

headers = {}

def get_std_headers(comp):
    with open("include/" + comp + ".hpp") as file:
        for line in file:
            inc_match  = inc_re.match(line)
            comp_match = comp_re.match(line)
            if inc_match and not comp_match:
                headers[inc_match.group(1)] = 1

def get_declarations(comp):
    with open("include/" + comp + ".hpp") as file:
        for line in file:
            if name_re.match(line):
                print(line)
                break

        for line in file:
            if end_re.match(line):
                break
            print(line[:-1])

print("""// include/unit.hpp                                                  -*-C++-*-
// ----------------------------------------------------------------------------
//  Copyright (C) 2020 Dietmar Kuehl http://www.dietmar-kuehl.de         
//                                                                       
//  Permission is hereby granted, free of charge, to any person          
//  obtaining a copy of this software and associated documentation       
//  files (the "Software"), to deal in the Software without restriction, 
//  including without limitation the rights to use, copy, modify,        
//  merge, publish, distribute, sublicense, and/or sell copies of        
//  the Software, and to permit persons to whom the Software is          
//  furnished to do so, subject to the following conditions:             
//                                                                       
//  The above copyright notice and this permission notice shall be       
//  included in all copies or substantial portions of the Software.      
//                                                                       
//  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,      
//  EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES      
//  OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND             
//  NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT          
//  HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,         
//  WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING         
//  FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR        
//  OTHER DEALINGS IN THE SOFTWARE. 
// ----------------------------------------------------------------------------
// This header is generated by combining the others, e.g., to make the
// implementation accessible on Compiler Explorer.

#ifndef INCLUDED_UNIT
#define INCLUDED_UNIT

""")

comps = sys.stdin.readlines()
comps = comps[::-1]
for comp in comps:
    comp = comp[:-1]
    get_std_headers(comp)

for header in headers.keys():
    print("#include <" + header + ">")

for comp in comps:
    comp = comp[:-1]
    get_declarations(comp)

print("")
print("#endif")
