.PHONY: default
default:
	cd ..; $(MAKE)

.PHONY: depend
depend:
	cd ..; $(MAKE) depend

.PHONY: all
all:
	cd ..; $(MAKE) all

.PHONY: todo
todo:
	cd ..; $(MAKE) todo

.PHONY: clean
clean:
	cd ..; $(MAKE) clean

.PHONY: clean-all
clean-all:
	cd ..; $(MAKE) clean-all
