#  Makefile                                                      -*-makefile-*-
#  ----------------------------------------------------------------------------

.PHONY: default
default: hazptr.t

CXXFLAGS = -W -Wall -std=c++17
